name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Build Web Release Bundle
        run: flutter build web --release

      - name: Install Firebase CLI & Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
